#!/usr/bin/env bash
# This script that installs nginx server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R $USER:$USER /var/www
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
