#!/usr/bin/env bash
# script that Install and configure HAproxy on your lb-01 server.
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script

sudo apt-get -y update
sudo apt-get -y install haproxy

server_config=\
"
backend mwesigwa2-backend
	balance roundrobin
	option forwardfor
	server 227378-web-01 54.164.27.186:80 check
	server 227378-web-02 52.86.142.105:80 check

frontend mwesigwa2-frontend
	bind *:80
	mode http
	default_backend mwesigwa2-backend
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
